defaults:
    compile:
        input: ./docs/adr
        plugin: netarchtest
plugin_configs:
    netarchtest:
        assembly-prefixes: TLAManager.
        output-dir: ./manager/src/TLAManager.Tests/ArchTests/Generated
