defaults:
    compile:
        input: ./docs/adr
        plugin: netarchtest
    verify:
        input: ./docs/adr
        plugin: fscheck
# TODO: move to service-specific config file
plugin_configs:
    netarchtest:
        assembly-prefixes: TLAManager.
        output-dir: ./manager/src/TLAManager.Services.Tests/ArchTests/Generated
