org: ${env:TLA_SAMPLE_APP_SERVERLESS_ORG}
app: tla-manager-serverless
service: tla-manager-serverless
provider:
  name: aws
  region: us-east-1
  runtime: dotnet10
  timeout: 10
  tracing:
    apiGateway: true
    lambda: true
  environment:
    TLA_TABLE_NAME: tla-manager-table-dev
    TLA_REPORT_TABLE_NAME: tla-report-table-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - !GetAtt TLADynamoDBTable.Arn
        - !GetAtt TLAReportTable.Arn
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource:
        - "arn:aws:events:*"

package:
  artifact: bin/release/net10.0/deploy-package.zip

resources:
  Resources:
    TLADynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "name"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "name"
            KeyType: "HASH"
        TableName: ${self:provider.environment.TLA_TABLE_NAME}
    TLAReportTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        TableName: ${self:provider.environment.TLA_REPORT_TABLE_NAME}

functions:
  readAllTlaGroups:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.GetAllTlaGroupsFunction::GetAllTlaGroupsAsync
    events:
      - httpApi:
          path: /tlas
          method: get
  addNewTlaGroup:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.AddTlaGroupFunction::AddTlaGroupAsync
    events:
      - httpApi:
          path: /tlas
          method: post
  addNewTla:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.AddTlaFunction::AddTlaAsync
    events:
      - httpApi:
          path: /tlas/{groupName}
          method: post
  acceptTla:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.AcceptTlaFunction::AcceptTlaAsync
    events:
      - httpApi:
          path: /tlas/{groupName}/{name}/accept
          method: put
  createReport:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.CreateTLAReportFunction::CreateTLAReportAsync
    events:
      - httpApi:
          path: /reports
          method: post
  report:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.TLAReportFunction::TLAReportAsync
    events:
      - httpApi:
          path: /reports/{id}
          method: get

  seedDatabase:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.Migration.DatabaseSeedHandler::SeedAsync
