stages:
  - build
  - deploy-services

.reports:
  before_script:
    - cd reports

build-reports:
  extends: .reports
  stage: build
  image: python:3.14
  script:
    - echo "Installing Python dependencies..."
    - pip install -r requirements.txt
    - echo "Validating report handler..."
    - python -m py_compile reports.py
    - echo "Reports service successfully built."
  artifacts:
    paths:
      - reports/reports.py
      - reports/requirements.txt
      - reports/serverless.yml

deploy-reports:
  extends: .reports
  stage: deploy-services
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
    TLA_SAMPLE_APP_SERVERLESS_ORG: $TLA_SAMPLE_APP_SERVERLESS_ORG
  only:
    refs:
      - main
  script:
    - echo "Deploying reports service..."
    - npm ci
    - sls deploy
    - echo "Reports service successfully deployed."
  dependencies: [build-reports]

undeploy-reports:
  extends: .reports
  stage: deploy-services
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
    TLA_SAMPLE_APP_SERVERLESS_ORG: $TLA_SAMPLE_APP_SERVERLESS_ORG
  when: manual
  only:
    refs:
      - main
  script:
    - echo "Undeploying reports service..."
    - npm ci
    - sls remove
    - echo "Reports service successfully undeployed."
  dependencies: [build-reports]
