stages:
  - build
  - deploy-services

.resolver:
  before_script:
    - cd resolver

build-resolver:
  extends: .resolver
  stage: build
  image: eclipse-temurin:21-jdk-noble
  script:
    - echo "Building application..."
    - ./mvnw clean package
    - echo "Application successfully built."
  artifacts:
    paths:
      - resolver/target/tla-resolver-serverless-${PROJECT_VERSION}-aws.jar

deploy-resolver:
  extends: .resolver
  stage: deploy-services
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
    TLA_SAMPLE_APP_SERVERLESS_ORG: $TLA_SAMPLE_APP_SERVERLESS_ORG
  only:
    refs:
      - main
  script:
    - echo "Deploying application..."
    - sls deploy
    - sls invoke --function seedDatabase --data 'unused'
    - echo "Application successfully deployed."
  dependencies: [build-resolver]

undeploy-resolver:
  extends: .resolver
  stage: deploy-services
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
    TLA_SAMPLE_APP_SERVERLESS_ORG: $TLA_SAMPLE_APP_SERVERLESS_ORG
  when: manual
  only:
    refs:
      - main
  script:
    - echo "Undeploying application..."
    - sls remove
    - echo "Application successfully undeployed."
  dependencies: [build-resolver]
