stages:
  - deploy-infrastructure
  - deploy-services

.infrastructure:
  before_script:
    - cd infrastructure

deploy-infrastructure:
  extends: .infrastructure
  stage: deploy-infrastructure
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
    TLA_SAMPLE_APP_SERVERLESS_ORG: $TLA_SAMPLE_APP_SERVERLESS_ORG
  only:
    refs:
      - main
  script:
    - echo "Deploying application..."
    - sls deploy
    - echo "Application successfully deployed."
  dependencies: []

undeploy-infrastructure:
  extends: .infrastructure
  stage: deploy-infrastructure
  image: $SLS_IMAGE
  environment: dev
  variables:
    SERVERLESS_ACCESS_KEY: $SERVERLESS_ACCESS_KEY
    TLA_SAMPLE_APP_SERVERLESS_ORG: $TLA_SAMPLE_APP_SERVERLESS_ORG
  when: manual
  only:
    refs:
      - main
  script:
    - echo "Undeploying application..."
    - sls remove
    - echo "Application successfully undeployed."
  dependencies: []
